/**
 * Deterministic OpenAPI → TypeScript + Zod generation (M0-T15).
 *
 * 1. Export OpenAPI from the FastAPI app (via uv).
 * 2. Write packages/contracts/openapi.json (sorted, stable).
 * 3. Generate TS types (openapi-typescript).
 * 4. Generate Zod schemas from response JSON Schemas (json-schema-to-zod).
 */
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const repoRoot = path.resolve(pkgRoot, "../..");
const openapiPath = path.join(pkgRoot, "openapi.json");
const srcDir = path.join(pkgRoot, "src");
const require = createRequire(path.join(pkgRoot, "package.json"));

function runNodeCli(packageName, binRelative, args) {
  const pkgJsonPath = require.resolve(`${packageName}/package.json`);
  const binPath = path.join(path.dirname(pkgJsonPath), binRelative);
  execFileSync(process.execPath, [binPath, ...args], {
    cwd: pkgRoot,
    stdio: "inherit",
    shell: false,
  });
}

function runUv(args) {
  const uv = process.platform === "win32" ? "uv.exe" : "uv";
  return execFileSync(uv, args, {
    cwd: repoRoot,
    encoding: "utf8",
    shell: false,
  });
}

function toSchemaExportName(operationId) {
  const pascal = operationId
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
  return `${pascal}ResponseSchema`;
}

function generateZodSchemas(document) {
  const lines = [
    "/**",
    " * This file was auto-generated by packages/contracts/scripts/generate.mjs.",
    " * Do not make direct changes to the file.",
    " */",
    'import { z } from "zod";',
    "",
  ];

  const paths = document.paths ?? {};
  const operationIds = [];
  for (const pathItem of Object.values(paths)) {
    for (const operation of Object.values(pathItem)) {
      if (!operation || typeof operation !== "object") continue;
      const operationId = operation.operationId;
      if (typeof operationId !== "string") continue;
      const schema =
        operation.responses?.["200"]?.content?.["application/json"]?.schema;
      if (!schema) continue;
      operationIds.push(operationId);
      const exportName = toSchemaExportName(operationId);
      const expression = jsonSchemaToZod(schema, {
        module: "none",
        name: exportName,
      });
      lines.push(`export ${expression};`);
      lines.push("");
    }
  }

  if (operationIds.length === 0) {
    lines.push("// No application/json 200 responses found in OpenAPI paths.");
    lines.push("");
  }

  return lines.join("\n");
}

mkdirSync(srcDir, { recursive: true });

const openapiJson = runUv([
  "run",
  "python",
  "packages/contracts/scripts/export_openapi.py",
]);

const document = JSON.parse(openapiJson);
const stable = `${JSON.stringify(document, null, 2)}\n`;
writeFileSync(openapiPath, stable, "utf8");

runNodeCli("openapi-typescript", "bin/cli.js", [
  "openapi.json",
  "-o",
  "src/types.ts",
]);

const schemasSource = generateZodSchemas(document);
writeFileSync(path.join(srcDir, "schemas.ts"), schemasSource.replace(/\r\n/g, "\n"), "utf8");

const typesRaw = readFileSync(path.join(srcDir, "types.ts"), "utf8");
writeFileSync(
  path.join(srcDir, "types.ts"),
  typesRaw.replace(/\r\n/g, "\n"),
  "utf8",
);

writeFileSync(
  path.join(srcDir, "index.ts"),
  [
    "/** Generated public surface for @career-os/contracts (M0-T15). */",
    'export type * from "./types";',
    'export * from "./schemas";',
    "",
  ].join("\n"),
  "utf8",
);

console.log("contracts: generated openapi.json, src/types.ts, src/schemas.ts");
