/**
 * This file was auto-generated by packages/contracts/scripts/generate.mjs.
 * Do not make direct changes to the file.
 */
import { z } from "zod";

export const HealthzHealthzGetResponseSchema = z.record(z.string(), z.string());

export const ReadyzReadyzGetResponseSchema = z.record(z.string(), z.any());
