"""Identity & Access bounded context."""

from careeros_identity.domain import (
    AccountDeletionRequested,
    AuthRef,
    Consent,
    ConsentGranted,
    ConsentId,
    ConsentPurpose,
    ConsentScope,
    ConsentWithdrawn,
    EmailAddress,
    User,
    UserEmailVerified,
    UserErased,
    UserId,
    UserRegistered,
    UserRole,
    UserStatus,
    UserSuspended,
)
from careeros_identity.ports import AuthProvider, UserRepository, VerifiedIdentity

__all__ = [
    "AccountDeletionRequested",
    "AuthProvider",
    "AuthRef",
    "Consent",
    "ConsentGranted",
    "ConsentId",
    "ConsentPurpose",
    "ConsentScope",
    "ConsentWithdrawn",
    "EmailAddress",
    "User",
    "UserEmailVerified",
    "UserErased",
    "UserId",
    "UserRegistered",
    "UserRepository",
    "UserRole",
    "UserStatus",
    "UserSuspended",
    "VerifiedIdentity",
]
